version: 2.1
jobs:
  test-build:
    working_directory: ~/gobom
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

      - run:
          name: Build
          command: go build ./cmd/gobom/

  check-golangci-lint:
    docker:
      - image: golangci/golangci-lint:v1.42.0
    steps:
      - checkout
      - run:
          command: golangci-lint run ./...


workflows:
  version: 2
  ci:
    jobs:
      - test-build
      - check-golangci-lint
